### ISSUE TITLE
How about domino 12.0.2 Restic settings?

### ISSUE THREAD

**Issue by yeehwong** [HCL-TECH-SOFTWARE/domino-backup#12]
HCL Product Version
V12.0.2FP2

Describe the issue
Use load backup command can't to run the restic snapshot backup, and the UI can't to restore .nsf file
**Use windows command take the backup & restore is working

Backup Error Message
[1E14:0002-1D78] 08.09.2023 01:20:30 PM Backup: Domino Database Backup
[1E14:0002-1D78] 08.09.2023 01:20:30 PM Backup: Started
[1E14:0002-1D78] 08.09.2023 01:20:30 PM Backup: Pruning backups
[1E14:0002-1D78] 08.09.2023 01:20:30 PM Backup: Pruned Database Backups: 13
[1E14:0002-1D78] 08.09.2023 01:20:30 PM Backup: BackupNode: [DOMINO12], BackupName: [default], Translog Mode: [CIRCULAR], Backup Mode: [FULL]
[1E14:0002-1D78] 08.09.2023 01:20:30 PM Backup: LastBackupTime: 06.09.2023 01:18:49 PM
[1E14:0002-1D78] 08.09.2023 01:20:31 PM Backup: Starting backup for 123 database(s) [*SnapShotMode*]
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Creating Snapshot
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Empty OS Level Command!
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Error Start-Snapshot Command: [] : File cannot be created
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup:
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: --- Backup Summary ---
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Previous Backup : 06.09.2023 01:18:49 PM
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Start Time : 08.09.2023 01:20:30 PM
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: End Time : 08.09.2023 01:20:32 PM
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Runtime : 00:00:01.656
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup:
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: [General ERROR!] - Error Start-Snapshot Command
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup:
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: All : 123
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Processed : 0
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Excluded : 0
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Pending Compact : 0
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Compact Retries : 0
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Backup Errors : 123
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Not Modified : 0
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Delta Files : 0
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Delta applied : 0
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup:
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Total DB Size : 0.0 Bytes
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Total DeltaSize : 0.0 Bytes
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Data Rate : 0.0 MB/sec
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: --- Backup Summary ---
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup:
[1E14:0002-1D78] 08.09.2023 01:20:32 PM Backup: Finished

UI Restore Error Message

C:\restic\restore_db.cmd "C:\Lotus\Domino\Data\AgentRunner.nsf" "AgentRunner.nsf" "" "DOMINO12" "" "SNAP" "20230906051849" "e:\snapshot\domino" "C:\Lotus\Domino\Data\restore\AgentRunner.nsf" ""

Active code page: 65001

[06.09.2023 13:29:12.54] --- Restore db from snapshot ---
PhysicalFileName : "C:\Lotus\Domino\Data\AgentRunner.nsf"
FileName         : "AgentRunner.nsf"
BackupReference  : ""
BackupNode       : "DOMINO12"
BackupName       : ""
BackupMode       : "SNAP"
BackupStartDT    : "20230906051849"
BackupTargetDir  : "e:\snapshot\domino"
RestoreFileName  : "C:\Lotus\Domino\Data\restore\AgentRunner.nsf"
All Paramters    : "C:\Lotus\Domino\Data\AgentRunner.nsf" "AgentRunner.nsf" "" "DOMINO12" "" "SNAP" "20230906051849" "e:\snapshot\domino" "C:\Lotus\Domino\Data\restore\AgentRunner.nsf" ""

BackupTagName: dominobackup_20230906051849.tag
RESTIC_BIN: C:\restic\restic.exe
TAG-FILE: dominobackup_20230906051849.tag
RESTIC_REPOSITORY: e:/snapshot/domino
C:\restic\restic.exe find dominobackup_20230906051849.tag

Searching for tag file [dominobackup_20230906051849.tag] in Ristic repository

Snapshot             : c38c17a97bf0b39849a3729d3f2065da70d114bf5958011ba2387c8ae6bac9f0
File         : /C/Lotus/Domino/Data/AgentRunner.nsf
Restore                : C:\Lotus\Domino\Data\restore\AgentRunner.nsf.DAD

Return: ERROR - Cannot restore file from backup - 1

Restore_DB.cmd
@echo off

REM --- Begin Configuration ---

set RESTIC_PASSWORD=P@ssw0rd
set RESTIC_DIR=C:\restic
set RESTIC_BIN=%RESTIC_DIR%\restic.exe
set JQ_BIN=%RESTIC_DIR%\jq.exe

REM --- End Configuration ---

REM Change Code Page to UTF-8
chcp 65001

set SNAPSHOT_ID_TMPFILE=%TEMP%\restic_snapshot_%~7.txt

set SOURCE=%~1
set RESTIC_REPOSITORY=%~8
set RESTIC_REPOSITORY=e:/snapshot/domino

set TARGET=%~9
set TARGET_DIR=%~dp9
set FILE_EXT=%~x9

REM Replace backslash to slash and remove drive separator

set SOURCE=%SOURCE:\=/%
set SOURCE=%SOURCE::=%
set SOURCE=/%SOURCE%

REM Unique tag used to verify the backup
set DOMBACK_TAG_FILE=dominobackup_%~7.tag

echo:
echo [%DATE% %TIME%] --- Restore db from snapshot ---
echo PhysicalFileName : %1
echo FileName         : %2
echo BackupReference  : %3
echo BackupNode       : %4
echo BackupName       : %5
echo BackupMode       : %6
echo BackupStartDT    : %7
echo BackupTargetDir  : %8
echo RestoreFileName  : %9
echo All Paramters    : %*
echo:

REM Find backup Via backup Tag file

echo BackupTagName: %DOMBACK_TAG_FILE%
echo RESTIC_BIN: %RESTIC_BIN%
echo TAG-FILE: %DOMBACK_TAG_FILE%
echo RESTIC_REPOSITORY: %RESTIC_REPOSITORY%
echo %RESTIC_BIN% find %DOMBACK_TAG_FILE%
echo.

if exist "%SNAPSHOT_ID_TMPFILE%" (
	echo Snapshot for tag [%DOMBACK_TAG_FILE%] already found
) else (
	echo Searching for tag file [%DOMBACK_TAG_FILE%] in Ristic repository
	"%RESTIC_BIN%" find "%DOMBACK_TAG_FILE%" --json | "%JQ_BIN%" .[0].snapshot > %SNAPSHOT_ID_TMPFILE%

	if %ERRORLEVEL% NEQ 0 (
	echo Return: ERROR - Cannot find file in backup - %ERRORLEVEL%
	exit /b 0
	)
)

set /p SNAPSHOT=<"%SNAPSHOT_ID_TMPFILE%"

REM Remove quotes
set SNAPSHOT=%SNAPSHOT:"=%

if not exist "%TARGET_DIR%" (
mkdir "%TARGET_DIR%"
)

if not "%FILE_EXT%"==".DAD" (
set TARGET=%TARGET%.DAD
)

echo.
echo Snapshot	: %SNAPSHOT%
echo File	: %SOURCE%
echo Restore 	: %TARGET%
echo.

REM Run restore command
"%RESTIC_BIN%" dump "%SNAPSHOTS%" "%SOURCE%" > "%TARGET%"

if %ERRORLEVEL% NEQ 0 (
echo Return: ERROR - Cannot restore file from backup - %ERRORLEVEL%
exit /b 0
)

if exist "%TARGET%" (
echo Return: PROCESSED
exit /b 0
)

echo Return: ERROR - Cannot find restored file

To Reproduce
Run the VSS backup. We use Restic backup

Screenshots
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/144640068/fb424a15-c604-4be2-b88c-2270091e41c5)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/144640068/63bb1271-46c9-4bee-8c58-3d4675f23a26)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/144640068/10c93d3e-7271-440a-8ee8-54042b756b44)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/144640068/96a73e9a-2967-4f79-87a4-331c8eda4050)

**Comment by Daniel-Nashed** [comment]
Hi and thanks for your interest in building your own integration.

Sadly we don't have the capacity to look into own implemented configurations in detail.
But let me give you some feedback and ideas.

You are trying to use Restic backup in the classical 12.0.1way without Domino VSS.
This isn't what I would recommend any more.

There is native VSS support since Domino 12.0.2 and I would recommend going this route.

Restic supports creating VSS snapshots and it generally works out with the Domino VSS Writer.
But my current state is that Restic does not support application consistent snapshots (auto recovery snapshots -- [VSS_VOLSNAP_ATTR_AUTORECOVER](https://learn.microsoft.com/en-us/windows/win32/api/vss/ne-vss-vss_volume_snapshot_attributes)). So you would still need to backup delta files -- which would need to be applied at restore time.

That makes it a bit more complicated. But is still the better way than the path you are trying.

If Restic would support auto recovery snapshots, there would be no integration needed for the backup part only for the restore part.

For backup VSS would trigger the backup. 

I have looked into Restic, but I stopped my integration efforts when Resitc did not have auto recovery snapshots.
This would not too difficult to add to Restic, but I am not a GO developer.. 

But also the restore part with Restic is a bit complicated.
There are ways to perform a restore. But not as expected. See the [issue](https://github.com/restic/restic/issues/4027) I raised in the Restic project a while ago.

But once the auto recovery snapshot would be implemented on their end, I would have a working restore_db.cmd for you.

Maybe we should raise an issue at Restic for auto recovery snapshot support or look into it again to see if they might have added it already. 

I really like Restic and I am using it for other backups. Having a solid Restic Domino VSS integration is high on my personal wish list as well.

Could you check if they have auto recovery snapshots since I last checked the project?
Else we might want to raise this with Restic.

Once they have auto recovery snapshots I would do the implementation for your and publish it ASAP :-)

Thanks

Daniel

**Comment by yeehwong** [comment]
Hi Daniel,

Thank you very much for your reply. Since we did not purchase Veeam and AWS S3, and it was mentioned in your video (Domino Backup and Restore (SUTOL Conference 2022)) that volume shadow copy and restic are free versions of the software, but only restic has more detailed settings and tests, So we chose to use restic for testing. However, we were never able to successfully restore using the UI, and HCL support suggested we check here. If you don't recommend Restic, do you have any other backup samples? Test Methods?

**Comment by Daniel-Nashed** [comment]
What are you trying to do? 
Is this for testing or production?
You can use Veeam for testing and you can even use the Veeam Community edition for free for up to 10 workloads!
If you are a small company and you are looking for a backup solution, Veeam Community edition would be a good way to go.

But usually you want a unified backup strategy and want all your backups using the same back-end.

So it is hard to tell without more information, what would be a good platform for you.

Restic is a cool backup application, but has some missing functionality to be easy to implement with Domino.
I used it for a demo and show how it can be integrated. But I did not add the delta files in this demo. 

What means "Test Methods"? Would you want it for production or just test out the functionality?

**Comment by yeehwong** [comment]
We are going to update the domin server to version 12.0.2, but since v12 has a vss backup function, we don't want to waste this function because we want to do a complete test before updating, because it is difficult for us to do this test again after updating. We originally thought that the dominobackup that comes with v12 can do VSS snapshot backup, but now it seems that we need to use other software to assist.

Moreover, the email data of our client company is also very large, so we want to use this snapshot solution to back up the data first, and then use software to back up the snapshot to a tape drive and other location.

**Comment by yeehwong** [comment]
We are going to update the domin server to version 12.0.2, but since v12 has a vss backup function, we don't want to waste this function because we want to do a complete test before updating, because it is difficult for us to do this test again after updating. We originally thought that the dominobackup that comes with v12 can do VSS snapshot backup, but now it seems that we need to use other software to assist.

Moreover, the email data of our client company is also very large, so we want to use this snapshot solution to back up the data first, and then use software to back up the snapshot to a tape drive and other locatioin.

**Comment by Daniel-Nashed** [comment]
Domino V12.0.2 introduces a new VSS Writer to be used with all software which supports VSS backups.
But this does not mean you don't need a backup software.

Domino backup is kind of a middle ware offering multiple integration options -- like Veeam.

With standard Backup space like a ZFS deduplicating and compressing storage, it can be a complete backup solution for smaller environments.

In larger environments you will need an enterprise backup solution, which would work hand in hand with the Domino backup VSS integration.

What type of backup do you have today? Which backup solution do you use for other applications/file servers?

**Comment by yeehwong** [comment]
Hi Daniel,

We use Acronis Backup to back up our existing domino servers and file servers.

**Comment by Daniel-Nashed** [comment]
Acronis should be also able to perform VSS snapshots. Why don't you check if Acronis could do a VSS auto recovery snapshot?

**Comment by yeehwong** [comment]
Hi Daniel,
Can you provide an example of a basic vss backup script for Acronis?

**Comment by Daniel-Nashed** [comment]
For the backup side there is no script needed.  the Domino backupvss servertask registers as VSS Writer.
VSS Writers are automatically triggered when the disk they are registered for is requested for a VSS snapshot.

Only for restore you would need a script. But without knowing Acronis it would be hard to tell what you would need.

**Comment by yeehwong** [comment]
Hi Daniel,
But I saw that veeam also needs to calculate backup_snapshot.cmd and backup_snapshot_start.cmd when running, and with acronis we only need to use the UI to restore mail.nsf on dominobackup.nsf.

**Comment by Daniel-Nashed** [comment]
Take a look into the Domino 12.0.2 Veeam documentation --> https://opensource.hcltechsw.com/domino-backup/backup-providers/veeam/install_vss_writer/

We rewrote it for Domino V12.0.2 and Veeam on Windows for VSS to simplify the configuration steps.

**Comment by yeehwong** [comment]
Hi Daniel,

I tested using veeam to do VSS backup, but the following error occurred when restoring using dominobackup.nsf:
----------------------------------------
c:\dominobackup\veeam\restore_db.cmd 2>&1 < NUL "D:\Lotus\Domino\Data\Mail\paulyeung.nsf" "Mail\paulyeung.nsf" "0D8F774367067E3348258A120028D07B" "MAIL3" "" "SNAP" "20230912064455" "c:\backup\nsf" "D:\Lotus\Domino\Data\restore\paulyeung.nsf" ""
----------------------------------------
Active code page: 65001

[Tue 09/12/2023 16:17:29.06] --- RESTORE DB from SNAPSHOT ---
PhysicalFileName  : "D:\Lotus\Domino\Data\Mail\paulyeung.nsf"
FileName          : "Mail\paulyeung.nsf"
BackupReference   : "0D8F774367067E3348258A120028D07B"
BackupNode        : "MAIL3"
BackupName        : ""
BackupMode        : "SNAP"
BackupStartDT     : "20230912064455"
BackupTargetDir   : "c:\backup\nsf"
RestoreFileName   : "D:\Lotus\Domino\Data\restore\paulyeung.nsf"
All Paramters     : "D:\Lotus\Domino\Data\Mail\paulyeung.nsf" "Mail\paulyeung.nsf" "0D8F774367067E3348258A120028D07B" "MAIL3" "" "SNAP" "20230912064455" "c:\backup\nsf" "D:\Lotus\Domino\Data\restore\paulyeung.nsf" ""

"Restore operations from snapshot"
Appending missing .DAD extension
Searching for backup tag before mounting [dominobackup_20230912064455.tag]

[Tue 09/12/2023 16:17:29.11] ----- Begin Mounting snaphot ----- 
ssh: connect to host 10.1.1.5 port 22: Connection refused
[Tue 09/12/2023 16:17:31.26] ----- End Mounting snaphot ----- 

Searching for backup tag after mounting [dominobackup_20230912064455.tag]

----- Search Results ----- 
TARGET            : D:\Lotus\Domino\Data\restore\paulyeung.nsf.DAD
FOUND_FILE_PATH   : []
FOUND_NOTESDATA   : []
----- Search Results ----- 

SOURCE: []

----------------------------------------
 

Since I am using multiple servers for continuous testing, I don’t know if there is anything else in restore.cmd that needs to be modified.

Veeam Backup Server IP: 10.1.1.5

Domino Server IP: 10.1.1.6 (Hyper-V in the Host Veeam Backup Server)

Backup Repository Server IP: 10.1.1.7 (E$)

Screen:
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/144640068/6e895a52-4dcd-45d6-b8fe-d9ebb3e2c8d7)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/144640068/b4ec63f9-dbbd-4b47-bcb2-42aba7ac4975)

**Comment by Daniel-Nashed** [comment]
The SSH connection fails. can you please go thru all the steps in the configuration to see where you might have missed a step.
If you can't get it working, you might need a business partner to help you.
The community project can't provide step by step help.

The connection between Domino and Veeam uses SSH which needs to be properly configured. Please check the steps in the documentation I referenced in my last reply.

**Comment by yeehwong** [comment]
Hi Daniel,
Finally, I have 2 questions to ask.
The first question is if there is no backup software, can dominobackup do snapshot backup and recovery?

The second question is if veeam is configured as a backup, if I want to do a snapshot backup of the domino every 2 hours, will veaam run it every 2 hours and then store the data in the repository?

**Comment by Daniel-Nashed** [comment]
Domino Backup itself does not perform any snapshots. It could be configured to trigger a snapshot and let a backup application back it up. That's the model introduced in Domino 12.

But because snapshots are difficult to coordinate with Domino changes that need to be applied (delta files documented in the GitHub repo) triggering the snapshot from outside and let Domino be involved in a VSS flow is the much better way to coordinate a snapshot backup.

In addition VSS Writer technology on Windows is exactly designed for this use case and is the de-facto standard for Windows backups today. 

Therefore if snapshot backup is needed on Windows, we are only supporting VSS and recommending to move to Domino 12.0.2.
On Linux there is no tight integration and Domino backup still needs to use a more complex way to implement snapshot functionality.  So for example for Veeam Domino on Linux still uses the implementation introduced in Domino 12.0.1 time frame. 
But for Domino on Windows you really should move to Domino 12.0.2 and the native VSS writer.

For Veeam I would not want to take a snapshot every two hours if not really needed. But in theory you could do exactly that.
Usually it is perfectly to do a daily snapshot and use circular or linear transaction logs to recover database changes for a couple of days and have daily snapshot backups.

But you would miss newly created databases during that time until the next snapshot.
If you have two servers in a cluster I would recommend backing up both servers to a different time.

Here would be my personal preference. 

1. Take a snapshot at lunch time on one server
2. Take a snapshot after daily operations finish on the other server
3. If really needed do another snapshot after nightly operations

I would personally not snapshot every 2 hours. Specially because each backup will be written to dominobackup.nsf. 
This would be 12 backups per day or maybe just for operation hours let's say 6 backups per day. Let's say you do that for week days only. This would be 30 backups per week already.Domino backup can handle like 100-120 backups in total because of the backup inventory is written into Notes documents. 

So I would not encourage you to use two hour snapshots!
But it would work.

**Comment by yeehwong** [comment]
Hi Daniel,
Did you suggest pruning snapshots during every daily backup, or running a scheduled prune snapshot after a certain date?

**Comment by Daniel-Nashed** [comment]
This question cannot be answered independent from the backup solution in place.
With Veeam the backup itself is consistent from NSF point of view (DAOS is backed up separately).
That means every backup could be restored also with Veeam mounting the backup and an admin copying data form the snapshot.

Also from security point of view it makes sense to not let Domino prune backups on the Veeam side (which would be technically not to difficult to implement but is not a good idea, because you want to protect your backups).

So backups can be pruned separately on Domino and on Veeam. Of course you could prune backups on the Domino side and I am assuming you want to do that to get more snapshots backed up. But this is clearly not the right way.  You should really not need to take snapshots every two hours!

When you prune backups on the Domino side it does the following

1. remove the backup from the inventory (document per database containing all information in which backup it is)
2. delete the log document for the backup which contains the backup log
3. removes the backup log from disk

Backup logs appended to the log document and into file system are optional and can be used to re-constuct the inventory (1.)
You can back them up into a separate location and could re-import them into dominobackup.nsf if needed. 
This should be clearly not the normal case for a restore and are more a disaster recovery option.

Also Veeam backup offers short term and longer term backups. You might have copy jobs moving backups to different locations.
Those are separate from the standard backup repository and can't be restored automatically with the restore scripts in the way they are build today -- and it would need a lot of effort to get it right for every customer.

So it really depends on what you want in your environment and what your requirements are when to purge the backup logs/inventory on the Domino side.

**Comment by yeehwong** [comment]
Hi Daniel,

Thanks you for your help. We have try the Acronis to take the VSS Snapshot backup is functional.
