### ISSUE TITLE
file copy command for dominobackup

### ISSUE THREAD

**Issue by yeehwong** [HCL-TECH-SOFTWARE/domino-backup#13]
We will eventually use Acronis for snapshot backup (Monday to Friday evening) and file backup (Monday to Friday at noon), but I saw that the backup page can set the pre-backup command and post-backup command for network disk connection, but our test network Disk backup is very slow, so we want to run file backup to backup nsf to another hard disk (exp: E:\), and then use cmd to backup nsf (E:\) and copy the file to the network disk (G:\), but use robocopy failed. I added c:\source\robocopy.cmd(robocopy E:\FileBackup\nsf\ G:\FileBackup\nsf\DOMINO12\ /V /E /mir) in the command bar after backup

Can I run the copy command after backup?
If not, can we use Windows Schedule to run the domino load backup command?

Error screen:
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/144640068/752a9902-9d95-4c84-87d3-13dcadd07d8b)

Error Log:
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/144640068/28834bdd-6976-458b-bed0-d02194acf80d)

**Comment by yeehwong** [comment]
If we want to use windows schedule to run the domino load backup command, does domino have this function?
If so, what command can be used?

**Comment by Daniel-Nashed** [comment]
With Acronis you would not schedule any Domino backup command. Domino backup is triggered via VSS.
You are mixing different technologies here. Also if you want a Domino file level backup, just schedule it via Domino program documents. It causes more issues than it solves scheduling it from the Windows side.

But this is not your main problem. You first have to get your backup right. I would focus on one way to backup via Acronis if they support VSS with application aware snapshots.

**Comment by thampel** [comment]
As stated before, Domino Backup provides the integration with exactly ONE backup solution, not two.
The main idea is to have a user interface built into Domino to manage your Domino backups so that administrators do NOT have to use 3rd party tools to manage a backup/restore.

Please start by setting up snapshot/VSS backup e.g. via Acronis. 

We can not provide the detailled instructions for all type of backup software as we dont have all the various backup solutions/vendors available for testing. So if you struggle to configure it, please reach out to a business partner or HCL Services for assistance. 

If you have this integration with Acronis configured, you are welcome to share your experience [here](https://github.com/HCL-TECH-SOFTWARE/domino-backup/tree/main/backup-providers)
