### ISSUE TITLE
"Error running OS Level Restore Command" when running a restore task

### ISSUE THREAD

**Issue by pcEnte-net** [HCL-TECH-SOFTWARE/domino-backup#19]
Hey, we are currently implementing the Veeam domino-backup solution on our Linux- and Windows based Dominoservers. When we try to restore a database the error "Error running OS Level Restore Command" occurs on both our Linux- and Windows servers. I guess it's a configuration error on our side but I can't figure out where. The logfiles aren't containing any information regarding this error. To test the restore functionality I deleted a test mail database and tried to restore it to it's original path; that's the used configuration for the restore job: 
![Restorejob dommail 03](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/74569848/66e262d3-5bbd-4544-b528-18828d39a209)
This is a screenshot from the restore tab of the domino backup and restore application:
![Restore Tab dommail 03](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/74569848/160bab08-28f3-4673-bd5e-37acf1b82b3b)
Both Linux- and Windows servers have the same scripts in the same places in the restore configuration. The SSH-connection is in configurated in the scripts and working. 
Thanks : )

**Comment by Daniel-Nashed** [comment]
A bit more information about your environment would be helpful.
Which version of Domino are you running and which integration on the Domino Backup site on Windows?
We recommend the VSS Backup integration and Domino 12.0.2
There is a separate documentation just for that.

But your problem is on restore. There should be a log file appended to the log document with all the details from the restore job. End to End Logging has been introduced in Domino 12.0.1 and should give you all the details from the restore script including information returned by SSH.

It's hard to tell without more logs what your problem could be. If the SSH connection is verified we really need to look into the logs.

**Comment by pcEnte-net** [comment]
We are currently testing the Veeam Backup on two domino servers (one Linux-, one Windows based server). The Veeam Server contains all Veeam modules (console, proxy, repositories, database). We are using domino 12.0.2 SP 3 on all servers, on windows the VSS backup integration is being used. But we are getting the same error while restoring on both our Linux and Windows servers ("Error running OS Level Restore Command"). This is also the entry that appears in the console log. If there are logs that provide deeper information I'm not aware of them existing/where to find them. I also verified the functionality of the SSH-connection with testing the keys (if a login is possible) and with running the restore_db script manually. Could there be anything that prevents the scripts from being executed after starting a Restore Operation?

**Comment by Daniel-Nashed** [comment]
In normal cases if the failure is not very low level the request document should have a attachment with the log data after the operation failed.

**Comment by pcEnte-net** [comment]
I checked that and unfortunately there is not attachment.

**Comment by Daniel-Nashed** [comment]
can you run the restore with debug enabled? 
1. create the restore document
2. load restore -v -V

It's really quite odd that you don't get any log. there must be some more general configuration issue.
maybe it does not find the cmd/bash scripts? 

Just to make sure, you have the cmd/batch files on your Domino server?

**Comment by pcEnte-net** [comment]
I found one configuration issue: The server name on the main tab of the backup configuration wasn't full qualified. So he was using the default configuration with no scripts or paths in it. I fixed that problem, after that I got a logfile attached to the restore job:

----------------------------------------
D:\dominobackup\veeam\restore_db.cmd "D:\HCL\Domino\Data\mail\hhecke.nsf" "mail\hhecke.nsf" "61E9C5589238EFE1C1258ADB006796F5" "d2-w-dommail-03" "" "SNAP" "20240311210929" "c:\backup\nsf" "D:\HCL\Domino\Data\mail\hhecke.nsf" ""
----------------------------------------
Aktive Codepage: 65001.

[14.03.2024 14:10:20,29] --- RESTORE DB from SNAPSHOT ---
PhysicalFileName  : "D:\HCL\Domino\Data\mail\hhecke.nsf"
FileName          : "mail\hhecke.nsf"
BackupReference   : "61E9C5589238EFE1C1258ADB006796F5"
BackupNode        : "d2-w-dommail-03"
BackupName        : ""
BackupMode        : "SNAP"
BackupStartDT     : "20240311210929"
BackupTargetDir   : "c:\backup\nsf"
RestoreFileName   : "D:\HCL\Domino\Data\mail\hhecke.nsf"
All Paramters     : "D:\HCL\Domino\Data\mail\hhecke.nsf" "mail\hhecke.nsf" "61E9C5589238EFE1C1258ADB006796F5" "d2-w-dommail-03" "" "SNAP" "20240311210929" "c:\backup\nsf" "D:\HCL\Domino\Data\mail\hhecke.nsf" ""

"Restore operations from snapshot"
Appending missing .DAD extension
Searching for backup tag before mounting [dominobackup_20240311210929.tag]

[14.03.2024 14:10:20,31] ----- Begin Mounting snaphot ----- 

-------------------------------------------------------------------------------------
Domino Backup for Veeam Restore
-------------------------------------------------------------------------------------
Command      : [mount]
Date         : [20240311210929]
Connect      : [172.24.64.144]
VM Host      : [d2-w-dommail-03]
RestoreOS    : [Windows]
Account      : [Administrator]
MountFUSE    : [False]
ClockSkewMin : [5]
-------------------------------------------------------------------------------------

Error: No admin account found
1
[14.03.2024 14:10:24,78] ----- End Mounting snaphot ----- 

Searching for backup tag after mounting [dominobackup_20240311210929.tag]

----- Search Results ----- 
TARGET            : D:\HCL\Domino\Data\mail\hhecke.nsf.DAD
FOUND_FILE_PATH   : []
FOUND_NOTESDATA   : []
----- Search Results ----- 

SOURCE: []

----------------------------------------

----------------------------------------
D:\dominobackup\veeam\restore_post.cmd "" "" "" "d2-w-dommail-03" "" "" "20240311210929" "" "" ""
----------------------------------------

[14.03.2024 14:10:24,85] ---- Begin Unmounting all mounted snapshots ----

-------------------------------------------------------------------------------------
Domino Backup for Veeam Restore
-------------------------------------------------------------------------------------
Command      : [unmount]
Date         : []
Connect      : [172.24.64.144]
VM Host      : [d2-w-dommail-03]
RestoreOS    : [Windows]
Account      : [Administrator]
MountFUSE    : [False]
ClockSkewMin : [5]
-------------------------------------------------------------------------------------

Info: No Backups Mounted
0
[14.03.2024 14:10:28,93] ---- End Unmounting all mounted snapshots ----

Return: PROCESSED ()
----------------------------------------

Does that mean he tries to open the SSH-connection to himself and ignoring the configuration in the restore_db script? At least hes showing it's own ip there. I actually set the variable in the script for the ssh connection:
set VEEAM_SERVER_SSH=notes@172.24.64.72
Or does "Error: No admin account found" mean that something with the connection to the veeam server (priviledges etc.) is wrong? It's an administrative account and the keys are tested.

**Comment by Daniel-Nashed** [comment]
First of all you don't need a configuration per server. You could do it per operating system.
But this is good progress. Now we are getting logs to work with :-)

Tip: The good part for OpenSource software (beside that it is free) is that you can look at the scripts.

In this case the Administrator account is not found in your Veeam configuration.
You must specify the admin user with a matching the account Description that matches your JSON config on the server (in your case "Administrator is found in the JSON config -- see your log).  

The error message is coming from the PowerShell script running on the Veeam server looking into the Veeam configuration.

Check this [link](https://github.com/HCL-TECH-SOFTWARE/domino-backup/blob/e06f9723fc4b2e91a56efce377700c8712d65cbe/backup-providers/veeam/veeam_server/dominobackup/DominoRestore.ps1#L184)

The script should be readable and gives you a good idea what it is looking for.
Veeam does distinct accounts by Description because the user name could be the same name with different credentials on different machines in your infrastructure.

**Comment by pcEnte-net** [comment]
Hey, thanks for your help, problem is solved. There was a problem regarding the RPC connectivity of our local user on the dominoserver. It seems like we have a policy that only grants domainusers the required access.
