### ISSUE TITLE
question about Domino backup options usage

### ISSUE THREAD

**Issue by GiannandreaS** [HCL-TECH-SOFTWARE/domino-backup#2]
Hello,
after a ticket opening with HCL support, as they requested, I will post my question also here in this GitHub repository.

In short: we are testing the usage of the new "backup" features available with Domino 12.
We would like to know if it's possible to perform a simple action, for example copying a file called end_backup.txt inside the target backup directory, after the backup task has been regularly completed.

From the InfoCenter, the related paragraph is reachable at the following link:
https://help.hcltechsw.com/domino/12.0.0/admin/admn_backupbackuptab.html
it seems there should be a couple of fields which could be helpful in our scenario, it means:
"Post-backup command" or "Backup OK string"

But we'not been able to find a single example about the proposal, the usage and the output of these 2 fields.
Let's say that, in general, it will be very useful having few samples about the usage of the options available in the configuration document.

Could you be so kind to share few examples about how to use the mentioned fields?

kind regards

Giannandrea

**Comment by Daniel-Nashed** [comment]
The `Backup OK string` and `Backup error string` settings are intended to check if a command execution was successful.

- If the backup error string occurs it is always an error
- If OK string is specified in the configuration and the text is not occurring in the log, this is also an error case

What you are looking for is the `Post-backup command` which will be executed when the backup is finished.  
This is the place to clean up resources, write separate logs etc. And you can use it to trigger post backup operations, like triggering a backup for delta files or the full backup. 

But again as discussed earlier. If you have an existing Domino backup application, I would not replace it just because it is not yet supported by the vendor for Domino 12.

If you have an existing backup integration, it already as a very tight integration and backup vendor support.
We will not duplicate and 3rd party functionality! 

The backup application is intended for unblocking customers with their corporate wide backup infrastructure, which is not Domino enabled.

-- Daniel

**Comment by GiannandreaS** [comment]
Thanks for your reply Daniel, I sincerely appreciate your insights.
Giannandrea
