### ISSUE TITLE
Domino Backup

### ISSUE THREAD

**Issue by wrosioara** [HCL-TECH-SOFTWARE/domino-backup#22]
It seems the Domino incremental backup process is not working (i.e., it is only backing up the mail.box, instead of the .nsf and .ntfs in my data directory).   I apologize, I don't know how else to explain this.  I have spoken to HCL first level support and they couldn't provide any help/solution.

**Comment by Daniel-Nashed** [comment]
This is really difficult to answer if you don't describe what is happening and how your setup is.
Maybe you begin describing or sharing your configuration and exactly explain what you mean by incremental backup and what you expect.

**1. Archive translog**
In this case you full backup one or multiple times per week and meanwhile only backup translogs (-t option)
In this case an incremental backup does backup databases which have a changed DBIID. 

**2. Circular or linear translog**

In this scenario Domino backup tries to find out which database have changed since the last backup and will only backup those databases (this is not really comparable with archive translog where the backup is guaranteed to not cause any gaps and allows roll forward to any point in time between the backups).

The backup also depends on what type of integration you use. 

- For a file back-end each database is backed up one after another
- For a snapshot backup all databases are put into backup mode at once and a snapshot is created

With snapshot backup you can still use transaction logging in archive style and roll forward to the points in time between the snapshots. But in that case you should have a daily snapshot.

In any case **incremental** backup means that any changed database needs to be fully backuped in circular style.
And in case of archive style backups the delta/incremental backup is performed backing up the translogs and only take a full backup copy of databases with changed DBIID.  

I hope this explains it a bit more and helps you to describe what exact behavior you see.

This is not difference than for any other Domino backup API aware application. 
Please provide more details.

**Comment by Daniel-Nashed** [comment]
Hi!
I never heard back. Please re-open if you have more detailed questions.

Thanks
Daniel
